### ISSUE TITLE
runtime error when installing packages using requirements.txt

### ISSUE THREAD

**Issue by JosephBChoi** [USTB-AI3DVIP/matsam#2]
`gala==0.5.dev0` is not available neither using pip nor conda. Could you share how to install gala 0.5.dev0?

**Comment by USTB-AI3DVIP** [comment]
We have updated the readme file. It gives the gala library link to which you can refer.

**Comment by JosephBChoi** [comment]
Thank you for the feedback. I tried the installation on the link, but still can't figure out to install  `gala==0.5.dev0`. 
This is the error message I got: 

```
ERROR: Could not find a version that satisfies the requirement gala==0.5.dev0 (from versions: 1.3, 1.4.1, 1.5, 1.6.1, 1.7.1, 1.8.1)
ERROR: No matching distribution found for gala==0.5.dev0
```
